services:
  - type: web
    name: world-watch
    env: docker
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    healthCheckPath: /api/healthz
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
